# In this directory, run the following command to build this builder.
# $ gcloud builds submit

steps:
# Build the App Engine version with python support for gcloud.
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg=MAVEN_VERSION=3.9.11-eclipse-temurin-21'
  - '-f'
  - 'Dockerfile.appengine'
  - '--tag=us-central1-docker.pkg.dev/$PROJECT_ID/custom-builder/mvn:appengine-java21'
  - '.'
  id: 'gcloud'

images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/custom-builder/mvn:appengine-java21'

timeout: 2400s
